serverFiles:
  prometheus.yml:
    remote_write:
      - url: "mimir-release-nginx.wickstack.svc.cluster.local/ap1/v1/push"
    scrape_configs:
      - job_name: 'ubuntu1-node-exporter-service'
        static_configs:
          - targets: ['ubuntu1exporter.wickstack.svc.cluster.local:9100']  
      - job_name: 'ubuntu2-node-exporter-service'
        static_configs:
          - targets: ['ubuntu2exporter.wickstack.svc.cluster.local:9200']  
rbac:
  create: true
releaseNamespace: "wickstack"